name: DAG Deploy

on:
  push:
    branches:
      - master
    paths:
      - dags/**
  workflow_dispatch:

jobs:
  deploy-dag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Upload DAGs to Composer bucket
        run: |
          gsutil cp dags/notification--lark-ceo/*.py gs://vnbi-composer-1/dags/
