name: DAG Deploy

on:
  push:
    branches:
      - master
    paths:
      - dags/**
      - .github/workflows/dag-deploy.yaml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload DAGs to Composer bucket
        run: |
          gsutil -m cp -r dags/notification--lark-ceo/*.py gs://vnbi-composer-1/dags/notification--lark-ceo/
