name: DAG Deploy

on:
  push:
    branches:
      - master
    paths:
      - dags/**
      - .github/workflows/dag-deploy.yaml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: voltaic-country-280607
          export_default_credentials: true

      - name: Sync DAGs to Composer bucket
        run: |
          gsutil -m rsync -d -r dags/notification-lark-ceo/ gs://vnbi-composer-1/dags/notification-lark-ceo/
