name: Build & Push Job Docker Image

on:
  push:
    branches:
      - master
    paths:
      - job/**
      - .github/workflows/job-image-build-push.yaml
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

env:
  IMAGE: us-docker.pkg.dev/voltaic-country-280607/docker-1/lark-jobs
  IMAGE_TAG: latest

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: voltaic-country-280607
          export_default_credentials: true

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./job
          file: ./job/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
