name: Job/Image Build Push

on:
  push:
    branches:
      - master
    paths:
      - job/**
      - .github/workflows/job-image-build-push.yaml
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

env:
  IMAGE_TAG: us-docker.pkg.dev/voltaic-country-280607/docker-1/send-notification-lark-ceo

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_TAG }}
          context: ./job
          target: production
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
